resolves #4324
RPTools/maptool pull request #4327
Opened 2023-10-17 19:24 UTC by Jmr3366

Updated with advice from thelsing.

2023-10-19 12:36 UTC, cwisniew requested changes

2023-10-19 12:36 UTC, cwisniew commented on src/main/java/net/rptools/maptool/client/AppActions.java
> +            File mapFile = chooser.getSelectedFile();
The break statement in the if should be in { } to match coding standards

2023-10-26 06:12 UTC, kwvanderlinde approved these changes

2023-11-03 13:50 UTC, cwisniew approved these changes

2023-11-03 13:56 UTC, merged