Refactor zone renderer
RPTools/maptool pull request #4447
Opened 2023-11-21 07:42 UTC by bubblobill

Progress towards resolving #3691 Refactoring ZoneRenderer

### Description of the Change
Moved some constants to ZoneRendererConstants
Split off grid rendering and grid adjustment methods to new class GridRenderer
Split off halo rendering to new class HaloRenderer

### Possible Drawbacks
none

### Documentation Notes
More progress on modularising zone renderer with two new rendering classes for grids and halos.

### Release Notes
N/A

2023-11-23 16:02 UTC, kwvanderlinde requested changes

2023-11-23 16:02 UTC, kwvanderlinde commented on src/main/java/net/rptools/maptool/client/ui/zone/renderer/ZoneRenderer.java
> +  final DebounceExecutor repaintDebouncer;
If the suggested changes are made in GridRenderer, we can make this `private` again.

2023-11-23 16:02 UTC, kwvanderlinde commented on src/main/java/net/rptools/maptool/client/ui/zone/renderer/GridRenderer.java
> +  }
We can merge these into the GridTool instead, which will avoid the need to expose the grid renderer publicly to the tool. Also there is a `GridChanged` event that will be fired when `Grid.setOffset()` or `Grid.setSize()` is called - `ZoneRenderer` already listens for that in order to repaint itself, so explicit requests to do so shouldn't be necessary.

2023-11-23 16:02 UTC, kwvanderlinde commented on src/main/java/net/rptools/maptool/client/ui/zone/renderer/ZoneRenderer.java
> +    if (!compositor.isInitialised()) compositor.setRenderer(this);
Let's initialize the renderers here as well. Noticing also that the grid renderer is redundantly checked.

2023-11-23 16:02 UTC, kwvanderlinde commented on src/main/java/net/rptools/maptool/client/ui/zone/renderer/ZoneRenderer.java
> +  protected static final ZoneRendererConstants constants = new ZoneRendererConstants();
No need to instantiate `ZoneRendererConstants`, it can be used statically where needed.

2023-11-23 20:29 UTC, bubblobill commented on src/main/java/net/rptools/maptool/client/ui/zone/renderer/ZoneRenderer.java
> +    if (!compositor.isInitialised()) compositor.setRenderer(this);
Not redundant.
Whilst the zoneRenderer is under construction we cannot pass it as an argument to the other renderers.
This/these ensure that the renderer is set on the renderers on the first run through.
Still going to group them all together at the start as requested.

2023-11-23 20:39 UTC, bubblobill commented
Changes made as requested.
Tested successfully.

2023-11-23 20:46 UTC, bubblobill commented
No idea why it's failing formatting. It's has its spotless apply.

2023-11-24 05:13 UTC, cwisniew commented
> No idea why it's failing formatting. It's had its spotless apply.

Is your fork up to date and running the version of spotless from the have 21 upgrade?

2023-11-24 08:42 UTC, bubblobill commented
Surprisingly, everything is in sync and up to date. Although it still won't compile *Grid* with Java 21 unless I comment out the offending *stopwatch* calls.
from gradle.build -> id "com.diffplug.spotless" version "6.22.0"

For the record, the two changes appear to be spotless induced and not the result of human fiddling:
     src/main/java/net/rptools/maptool/client/ui/ColorComboBoxRenderer.java
     src/main/java/net/rptools/maptool/util/GraphicsUtil.java 

Also, found an issue with HaloRenderer where I was using the wrong bounds for the token.

2023-12-01 06:52 UTC, kwvanderlinde approved these changes

2023-12-01 10:03 UTC, merged